postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

auth: &auth
  username: Kath
  password:

development:
  <<: *auth
  <<: *postgres
  database: product_development

test:
  <<: *auth
  <<: *postgres
  database: product_test

production:
  <<: *auth
  <<: *postgres
  database: product_development
